/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { KritzelTool } from "./interfaces/tool.interface";
export { KritzelTool } from "./interfaces/tool.interface";
export namespace Components {
    interface KritzelControls {
    }
    interface KritzelEngine {
        "activeTool": KritzelTool;
    }
}
declare global {
    interface HTMLKritzelControlsElement extends Components.KritzelControls, HTMLStencilElement {
    }
    var HTMLKritzelControlsElement: {
        prototype: HTMLKritzelControlsElement;
        new (): HTMLKritzelControlsElement;
    };
    interface HTMLKritzelEngineElement extends Components.KritzelEngine, HTMLStencilElement {
    }
    var HTMLKritzelEngineElement: {
        prototype: HTMLKritzelEngineElement;
        new (): HTMLKritzelEngineElement;
    };
    interface HTMLElementTagNameMap {
        "kritzel-controls": HTMLKritzelControlsElement;
        "kritzel-engine": HTMLKritzelEngineElement;
    }
}
declare namespace LocalJSX {
    interface KritzelControls {
    }
    interface KritzelEngine {
        "activeTool"?: KritzelTool;
    }
    interface IntrinsicElements {
        "kritzel-controls": KritzelControls;
        "kritzel-engine": KritzelEngine;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kritzel-controls": LocalJSX.KritzelControls & JSXBase.HTMLAttributes<HTMLKritzelControlsElement>;
            "kritzel-engine": LocalJSX.KritzelEngine & JSXBase.HTMLAttributes<HTMLKritzelEngineElement>;
        }
    }
}
