'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type ActiveWorkspaceChangeEvent, type EditorIsReadyEvent, type IKritzelIsPublicChangeEvent, type IKritzelMenuItem, type IKritzelMenuItemSelectEvent, type IKritzelMenuItemToggleChildMenuEvent, type KritzelBaseObject, type KritzelEditorCustomEvent, type KritzelSettingsConfig, type KritzelSettingsCustomEvent, type KritzelShapeFillCustomEvent, type KritzelShareDialogCustomEvent, type KritzelSplitButtonCustomEvent, type KritzelStrokeSizeCustomEvent, type KritzelUndoState, type KritzelViewportState, type LocaleCode, type LoginEvent, type ObjectsAddedEvent, type ObjectsRemovedEvent, type ObjectsUpdatedEvent, type ShapeFillType, type ThemeName } from "@kritzel/editor";
import type { Components } from "@kritzel/editor/dist/components";
import { KritzelEditor as KritzelEditorElement, defineCustomElement as defineKritzelEditor } from "@kritzel/editor/dist/components/kritzel-editor.js";
import { KritzelSettings as KritzelSettingsElement, defineCustomElement as defineKritzelSettings } from "@kritzel/editor/dist/components/kritzel-settings.js";
import { KritzelShapeFill as KritzelShapeFillElement, defineCustomElement as defineKritzelShapeFill } from "@kritzel/editor/dist/components/kritzel-shape-fill.js";
import { KritzelShareDialog as KritzelShareDialogElement, defineCustomElement as defineKritzelShareDialog } from "@kritzel/editor/dist/components/kritzel-share-dialog.js";
import { KritzelSplitButton as KritzelSplitButtonElement, defineCustomElement as defineKritzelSplitButton } from "@kritzel/editor/dist/components/kritzel-split-button.js";
import { KritzelStrokeSize as KritzelStrokeSizeElement, defineCustomElement as defineKritzelStrokeSize } from "@kritzel/editor/dist/components/kritzel-stroke-size.js";

export type KritzelEditorEvents = {
    onIsReady: EventName<KritzelEditorCustomEvent<EditorIsReadyEvent>>,
    onActiveWorkspaceChange: EventName<KritzelEditorCustomEvent<ActiveWorkspaceChangeEvent>>,
    onObjectsChange: EventName<KritzelEditorCustomEvent<KritzelBaseObject[]>>,
    onObjectsAdded: EventName<KritzelEditorCustomEvent<ObjectsAddedEvent>>,
    onObjectsRemoved: EventName<KritzelEditorCustomEvent<ObjectsRemovedEvent>>,
    onObjectsUpdated: EventName<KritzelEditorCustomEvent<ObjectsUpdatedEvent>>,
    onObjectsSelectionChange: EventName<KritzelEditorCustomEvent<KritzelBaseObject[]>>,
    onUndoStateChange: EventName<KritzelEditorCustomEvent<KritzelUndoState>>,
    onThemeChange: EventName<KritzelEditorCustomEvent<ThemeName>>,
    onLocaleChange: EventName<KritzelEditorCustomEvent<LocaleCode>>,
    onViewportChange: EventName<KritzelEditorCustomEvent<KritzelViewportState>>,
    onLogout: EventName<KritzelEditorCustomEvent<void>>,
    onLogin: EventName<KritzelEditorCustomEvent<LoginEvent>>,
    onIsPublicChange: EventName<KritzelEditorCustomEvent<IKritzelIsPublicChangeEvent>>,
    onAwarenessChange: EventName<KritzelEditorCustomEvent<Map<number, Record<string, any>>>>
};

export const KritzelEditor: StencilReactComponent<KritzelEditorElement, KritzelEditorEvents, Components.KritzelEditor> = /*@__PURE__*/ createComponent<KritzelEditorElement, KritzelEditorEvents, Components.KritzelEditor>({
    tagName: 'kritzel-editor',
    elementClass: KritzelEditorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onIsReady: 'isReady',
        onActiveWorkspaceChange: 'activeWorkspaceChange',
        onObjectsChange: 'objectsChange',
        onObjectsAdded: 'objectsAdded',
        onObjectsRemoved: 'objectsRemoved',
        onObjectsUpdated: 'objectsUpdated',
        onObjectsSelectionChange: 'objectsSelectionChange',
        onUndoStateChange: 'undoStateChange',
        onThemeChange: 'themeChange',
        onLocaleChange: 'localeChange',
        onViewportChange: 'viewportChange',
        onLogout: 'logout',
        onLogin: 'login',
        onIsPublicChange: 'isPublicChange',
        onAwarenessChange: 'awarenessChange'
    } as KritzelEditorEvents,
    defineCustomElement: defineKritzelEditor
});

export type KritzelSettingsEvents = { onSettingsChange: EventName<KritzelSettingsCustomEvent<KritzelSettingsConfig>> };

export const KritzelSettings: StencilReactComponent<KritzelSettingsElement, KritzelSettingsEvents, Components.KritzelSettings> = /*@__PURE__*/ createComponent<KritzelSettingsElement, KritzelSettingsEvents, Components.KritzelSettings>({
    tagName: 'kritzel-settings',
    elementClass: KritzelSettingsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSettingsChange: 'settingsChange' } as KritzelSettingsEvents,
    defineCustomElement: defineKritzelSettings
});

export type KritzelShapeFillEvents = { onValueChange: EventName<KritzelShapeFillCustomEvent<ShapeFillType>> };

export const KritzelShapeFill: StencilReactComponent<KritzelShapeFillElement, KritzelShapeFillEvents, Components.KritzelShapeFill> = /*@__PURE__*/ createComponent<KritzelShapeFillElement, KritzelShapeFillEvents, Components.KritzelShapeFill>({
    tagName: 'kritzel-shape-fill',
    elementClass: KritzelShapeFillElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as KritzelShapeFillEvents,
    defineCustomElement: defineKritzelShapeFill
});

export type KritzelShareDialogEvents = {
    onToggleIsPublic: EventName<KritzelShareDialogCustomEvent<boolean>>,
    onDialogClosed: EventName<KritzelShareDialogCustomEvent<void>>
};

export const KritzelShareDialog: StencilReactComponent<KritzelShareDialogElement, KritzelShareDialogEvents, Components.KritzelShareDialog> = /*@__PURE__*/ createComponent<KritzelShareDialogElement, KritzelShareDialogEvents, Components.KritzelShareDialog>({
    tagName: 'kritzel-share-dialog',
    elementClass: KritzelShareDialogElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onToggleIsPublic: 'toggleIsPublic',
        onDialogClosed: 'dialogClosed'
    } as KritzelShareDialogEvents,
    defineCustomElement: defineKritzelShareDialog
});

export type KritzelSplitButtonEvents = {
    onMainButtonClick: EventName<KritzelSplitButtonCustomEvent<void>>,
    onItemSelect: EventName<KritzelSplitButtonCustomEvent<IKritzelMenuItemSelectEvent>>,
    onItemSave: EventName<KritzelSplitButtonCustomEvent<IKritzelMenuItem>>,
    onItemCancel: EventName<KritzelSplitButtonCustomEvent<IKritzelMenuItem>>,
    onItemToggleChildMenu: EventName<KritzelSplitButtonCustomEvent<IKritzelMenuItemToggleChildMenuEvent>>,
    onItemCloseChildMenu: EventName<KritzelSplitButtonCustomEvent<IKritzelMenuItem>>,
    onMenuOpen: EventName<KritzelSplitButtonCustomEvent<void>>,
    onMenuClose: EventName<KritzelSplitButtonCustomEvent<void>>
};

export const KritzelSplitButton: StencilReactComponent<KritzelSplitButtonElement, KritzelSplitButtonEvents, Components.KritzelSplitButton> = /*@__PURE__*/ createComponent<KritzelSplitButtonElement, KritzelSplitButtonEvents, Components.KritzelSplitButton>({
    tagName: 'kritzel-split-button',
    elementClass: KritzelSplitButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMainButtonClick: 'mainButtonClick',
        onItemSelect: 'itemSelect',
        onItemSave: 'itemSave',
        onItemCancel: 'itemCancel',
        onItemToggleChildMenu: 'itemToggleChildMenu',
        onItemCloseChildMenu: 'itemCloseChildMenu',
        onMenuOpen: 'menuOpen',
        onMenuClose: 'menuClose'
    } as KritzelSplitButtonEvents,
    defineCustomElement: defineKritzelSplitButton
});

export type KritzelStrokeSizeEvents = { onSizeChange: EventName<KritzelStrokeSizeCustomEvent<number>> };

export const KritzelStrokeSize: StencilReactComponent<KritzelStrokeSizeElement, KritzelStrokeSizeEvents, Components.KritzelStrokeSize> = /*@__PURE__*/ createComponent<KritzelStrokeSizeElement, KritzelStrokeSizeEvents, Components.KritzelStrokeSize>({
    tagName: 'kritzel-stroke-size',
    elementClass: KritzelStrokeSizeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSizeChange: 'sizeChange' } as KritzelStrokeSizeEvents,
    defineCustomElement: defineKritzelStrokeSize
});
