export { DIRECTIVES } from './lib/index';
export * from './lib/proxy';
export * from './lib/provide.function';

export {
    KritzelBaseObject,
    KritzelText,
    KritzelPath,
    KritzelImage,
    KritzelLine,
    KritzelShape,
    KritzelGroup,
    KritzelDynamicObject,
    KritzelIframeObject,
    KritzelDynamicObjectRendererRegistry,
    KritzelFontRegistry,
    KritzelBaseTool,
    KritzelBrushTool,
    KritzelTextTool,
    KritzelLineTool,
    KritzelShapeTool,
    KritzelEraserTool,
    KritzelSelectionTool,
    KritzelImageTool,
    KritzelWorkspace,
    InMemorySyncProvider,
    IndexedDBSyncProvider,
    BroadcastSyncProvider,
    WebSocketSyncProvider,
    HocuspocusSyncProvider,
    KritzelThemeManager,
    KritzelLocalizationManager,
    KritzelLicenseManager,
    ShapeType,
    KritzelAlignment,
    lightTheme,
    darkTheme,
    EN_LOCALE,
    DE_LOCALE,
    FR_LOCALE,
    DEFAULT_BRUSH_CONFIG,
    DEFAULT_TEXT_CONFIG,
    DEFAULT_SHAPE_CONFIG,
    hasRemoteSyncProvider,
} from '@kritzel/engine';

export type { HTMLKritzelEditorElement } from '@kritzel/editor';

export type {
    HTMLKritzelEngineElement,
    KritzelToolDefinition,
    KritzelDynamicObjectRenderer,
    KritzelDynamicObjectRenderContext,
    KritzelToolbarItem,
    KritzelBrushToolConfig,
    KritzelLineToolConfig,
    KritzelShapeToolConfig,
    KritzelTextToolConfig,
    KritzelTextConfig,
    KritzelShapeConfig,
    KritzelLineConfig,
    KritzelPathConfig,
    KritzelImageConfig,
    KritzelGroupConfig,
    KritzelDynamicObjectConfig,
    KritzelIframeContent,
    KritzelIframeObjectConfig,
    KritzelIframeObjectLifecycleContext,
    KritzelEmbeddedObject,
    KritzelWorkspaceConfig,
    KritzelFontDefinition,
    KritzelFontRegistration,
    KritzelRegisteredFont,
    KritzelFontMap,
    KritzelSyncConfig,
    KritzelTheme,
    KritzelViewportState,
    ContextMenuItem,
    KritzelObjectExportFormat,
    KritzelObjectExportContext,
    KritzelExportable,
    ThemeAwareColor,
    ThemeName,
    KritzelLocale,
    LocaleCode,
    KritzelTerms,
    KritzelTermKey,
    KritzelTermVars,
    KritzelLoginConfig,
    KritzelLoginProvider,
    LoginEvent,
    EditorIsReadyEvent,
    ActiveWorkspaceChangeEvent,
    ObjectsAddedEvent,
    ObjectsRemovedEvent,
    ObjectsUpdatedEvent,
    ObjectsInViewportChangeEvent,
    KritzelUndoState,
    IKritzelIsPublicChangeEvent,
    KritzelEngineState,
    KritzelDebugInfo,
    IKritzelUser,
} from '@kritzel/engine';