import { KritzelBaseObject } from "../classes/objects/base-object.class";
import { KritzelPath } from "../classes/objects/path.class";
import { KrtizelSelectionBox } from "../classes/objects/selection-box.class";
import { KritzelSelectionGroup } from "../classes/objects/selection-group.class";
import { KritzelText } from "../classes/objects/text.class";
import { KritzelOctree } from "../classes/structures/octree.structure";
import { KritzelBaseTool } from "../classes/tools/base-tool.class";
import { KritzelHandleType } from "../enums/handle-type.enum";
import { ContextMenuItem } from "./context-menu-item.interface";
import { KritzelDebugInfo } from "./debug-info.interface";

export interface KritzelEngineState {
  activeTool: KritzelBaseTool;
  activeText: KritzelText;
  currentPath?: KritzelPath;
  copiedObjects?: KritzelSelectionGroup;
  objectsOctree: KritzelOctree<KritzelBaseObject<Element>>;
  selectionBox?: KrtizelSelectionBox;
  selectionGroup?: KritzelSelectionGroup;
  resizeHandleType: KritzelHandleType;
  hasViewportChanged: boolean;
  isReady: boolean;
  isEnabled: boolean;
  isScaling: boolean;
  isPanning: boolean;
  isFocused: boolean;
  isSelecting: boolean;
  isResizing: boolean;
  isResizeHandleSelected: boolean;
  isRotating: boolean;
  isRotationHandleSelected: boolean;
  isDragging: boolean;
  isDrawing: boolean;
  isErasing: boolean;
  isWriting: boolean;
  isCtrlKeyPressed: boolean;
  isContextMenuVisible: boolean;
  contextMenuItems: ContextMenuItem[];
  contextMenuX: number;
  contextMenuY: number;
  skipContextMenu: boolean;
  debugInfo: KritzelDebugInfo;
  host: HTMLElement;
  cursorX: number;
  cursorY: number;
  scale: number;
  scaleMax: number;
  scaleMin: number;
  scaleStep: number;
  startX: number;
  startY: number;
  translateX: number;
  translateY: number;
  viewportWidth: number;
  viewportHeight: number;
  historyBufferSize: number;
  longTouchTimeout: number;
  longTouchDelay: number;
  pointers: Map<number, PointerEvent>;
}