import type { RouteRecordSingleView } from 'vue-router'

export const demoCategories = [
  { id: 'getting-started', title: 'Getting Started' },
  { id: 'fundamentals', title: 'Fundamentals' },
  { id: 'advanced', title: 'Advanced' },
  { id: 'customization', title: 'Customization' },
  { id: 'examples', title: 'Examples' },
] as const

export type DemoCategory = (typeof demoCategories)[number]

export interface DemoRoute {
  path: `/${string}`
  title: string
  category: DemoCategory['id']
  context?: string
  hidden?: boolean
  component: RouteRecordSingleView['component']
}

export const demoRoutes = [
  {
    path: '/getting-started/quick-start',
    title: 'Quick Start',
    category: 'getting-started',
    component: () => import('./pages/getting-started/QuickStartPage.vue'),
  },
  {
    path: '/getting-started/basic-usage',
    title: 'Basic Usage',
    category: 'getting-started',
    component: () => import('./pages/getting-started/BasicUsagePage.vue'),
  },
  {
    path: '/fundamentals/controls/context-menus-canvas-quick-actions',
    title: 'Context Menus Canvas Quick Actions',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/ContextMenusCanvasQuickActionsPage.vue'),
  },
  {
    path: '/fundamentals/controls/context-menus-clipboard-actions',
    title: 'Context Menus Clipboard Actions',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/ContextMenusClipboardActionsPage.vue'),
  },
  {
    path: '/fundamentals/controls/context-menus-smart-conditional',
    title: 'Context Menus Smart Conditional',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/ContextMenusSmartConditionalPage.vue'),
  },
  {
    path: '/fundamentals/controls/context-menus-object-inspector',
    title: 'Context Menus Object Inspector',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/ContextMenusObjectInspectorPage.vue'),
  },
  {
    path: '/fundamentals/controls/notifications-trigger',
    title: 'Notifications Trigger',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/NotificationsTriggerPage.vue'),
  },
  {
    path: '/fundamentals/controls/export-dialog',
    title: 'Export Dialog',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/ExportDialogPage.vue'),
  },
  {
    path: '/fundamentals/controls/import-dialog',
    title: 'Import Dialog',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/ImportDialogPage.vue'),
  },
  {
    path: '/fundamentals/controls/workspace-manager-open',
    title: 'Workspace Manager Open',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/WorkspaceManagerOpenPage.vue'),
  },
  {
    path: '/fundamentals/controls/more-menu-open',
    title: 'More Menu Open',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/MoreMenuOpenPage.vue'),
  },
  {
    path: '/fundamentals/controls/toolbar-utility-panel',
    title: 'Toolbar Utility Panel',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/ToolbarUtilityPanelPage.vue'),
  },
  {
    path: '/fundamentals/controls/zoom-panel-toggle',
    title: 'Zoom Panel Toggle',
    category: 'fundamentals',
    context: 'Controls',
    component: () => import('./pages/fundamentals/controls/ZoomPanelTogglePage.vue'),
  },
  {
    path: '/fundamentals/objects/add',
    title: 'Add',
    category: 'fundamentals',
    context: 'Objects',
    component: () => import('./pages/fundamentals/objects/ObjectsAddPage.vue'),
  },
  {
    path: '/fundamentals/objects/remove',
    title: 'Remove',
    category: 'fundamentals',
    context: 'Objects',
    component: () => import('./pages/fundamentals/objects/ObjectsRemovePage.vue'),
  },
  {
    path: '/fundamentals/objects/update',
    title: 'Update',
    category: 'fundamentals',
    context: 'Objects',
    component: () => import('./pages/fundamentals/objects/ObjectsUpdatePage.vue'),
  },
  {
    path: '/fundamentals/objects/filter',
    title: 'Filter',
    category: 'fundamentals',
    context: 'Objects',
    component: () => import('./pages/fundamentals/objects/ObjectsFilterPage.vue'),
  },
  {
    path: '/fundamentals/objects/selection',
    title: 'Selection',
    category: 'fundamentals',
    context: 'Objects',
    component: () => import('./pages/fundamentals/objects/ObjectsSelectionPage.vue'),
  },
  {
    path: '/fundamentals/objects/grouping',
    title: 'Grouping',
    category: 'fundamentals',
    context: 'Objects',
    component: () => import('./pages/fundamentals/objects/ObjectsGroupingPage.vue'),
  },
  {
    path: '/fundamentals/objects/ordering',
    title: 'Ordering',
    category: 'fundamentals',
    context: 'Objects',
    component: () => import('./pages/fundamentals/objects/ObjectsOrderingPage.vue'),
  },
  {
    path: '/fundamentals/tools/disable',
    title: 'Disable',
    category: 'fundamentals',
    context: 'Tools',
    component: () => import('./pages/fundamentals/tools/ToolsDisablePage.vue'),
  },
  {
    path: '/fundamentals/tools/toolbar',
    title: 'Toolbar',
    category: 'fundamentals',
    context: 'Tools',
    component: () => import('./pages/fundamentals/tools/ToolsToolbarPage.vue'),
  },
  {
    path: '/fundamentals/tools/config',
    title: 'Config',
    category: 'fundamentals',
    context: 'Tools',
    component: () => import('./pages/fundamentals/tools/ToolsConfigPage.vue'),
  },
  {
    path: '/fundamentals/tools/register',
    title: 'Register',
    category: 'fundamentals',
    context: 'Tools',
    component: () => import('./pages/fundamentals/tools/ToolsRegisterPage.vue'),
  },
  {
    path: '/fundamentals/tools/change',
    title: 'Change',
    category: 'fundamentals',
    context: 'Tools',
    component: () => import('./pages/fundamentals/tools/ToolsChangePage.vue'),
  },
  {
    path: '/fundamentals/viewport/pan',
    title: 'Pan',
    category: 'fundamentals',
    context: 'Viewport',
    component: () => import('./pages/fundamentals/viewport/ViewportPanPage.vue'),
  },
  {
    path: '/fundamentals/viewport/zoom',
    title: 'Zoom',
    category: 'fundamentals',
    context: 'Viewport',
    component: () => import('./pages/fundamentals/viewport/ViewportZoomPage.vue'),
  },
  {
    path: '/fundamentals/viewport/center',
    title: 'Center',
    category: 'fundamentals',
    context: 'Viewport',
    component: () => import('./pages/fundamentals/viewport/ViewportCenterPage.vue'),
  },
  {
    path: '/fundamentals/viewport/limits',
    title: 'Limits',
    category: 'fundamentals',
    context: 'Viewport',
    component: () => import('./pages/fundamentals/viewport/ViewportLimitsPage.vue'),
  },
  {
    path: '/fundamentals/viewport/boundaries',
    title: 'Boundaries',
    category: 'fundamentals',
    context: 'Viewport',
    component: () => import('./pages/fundamentals/viewport/ViewportBoundariesPage.vue'),
  },
  {
    path: '/fundamentals/viewport/events',
    title: 'Events',
    category: 'fundamentals',
    context: 'Viewport',
    component: () => import('./pages/fundamentals/viewport/ViewportEventsPage.vue'),
  },
  {
    path: '/fundamentals/workspaces/switch',
    title: 'Switch',
    category: 'fundamentals',
    context: 'Workspaces',
    component: () => import('./pages/fundamentals/workspaces/WorkspacesSwitchPage.vue'),
  },
  {
    path: '/fundamentals/workspaces/create',
    title: 'Create',
    category: 'fundamentals',
    context: 'Workspaces',
    component: () => import('./pages/fundamentals/workspaces/WorkspacesCreatePage.vue'),
  },
  {
    path: '/fundamentals/workspaces/read',
    title: 'Read',
    category: 'fundamentals',
    context: 'Workspaces',
    component: () => import('./pages/fundamentals/workspaces/WorkspacesReadPage.vue'),
  },
  {
    path: '/fundamentals/workspaces/update',
    title: 'Update',
    category: 'fundamentals',
    context: 'Workspaces',
    component: () => import('./pages/fundamentals/workspaces/WorkspacesUpdatePage.vue'),
  },
  {
    path: '/fundamentals/workspaces/delete',
    title: 'Delete',
    category: 'fundamentals',
    context: 'Workspaces',
    component: () => import('./pages/fundamentals/workspaces/WorkspacesDeletePage.vue'),
  },
  {
    path: '/fundamentals/persistence/memory',
    title: 'Memory',
    category: 'fundamentals',
    context: 'Persistence',
    component: () => import('./pages/fundamentals/persistence/PersistenceMemoryPage.vue'),
  },
  {
    path: '/fundamentals/persistence/local',
    title: 'Local',
    category: 'fundamentals',
    context: 'Persistence',
    component: () => import('./pages/fundamentals/persistence/PersistenceLocalPage.vue'),
  },
  {
    path: '/advanced/collaboration-local',
    title: 'Collaboration Local',
    category: 'advanced',
    hidden: true,
    component: () => import('./pages/advanced/collaboration/CollaborationLocalPage.vue'),
  },
  {
    path: '/advanced/collaboration-realtime',
    title: 'Collaboration Realtime',
    category: 'advanced',
    hidden: true,
    component: () => import('./pages/advanced/collaboration/CollaborationRealtimePage.vue'),
  },
  {
    path: '/advanced/user-management/providers',
    title: 'Providers',
    category: 'advanced',
    context: 'User Management',
    component: () => import('./pages/advanced/user-management/UserManagementProvidersPage.vue'),
  },
  {
    path: '/advanced/user-management/login',
    title: 'Login',
    category: 'advanced',
    context: 'User Management',
    component: () => import('./pages/advanced/user-management/UserManagementLoginPage.vue'),
  },
  {
    path: '/advanced/user-management/users',
    title: 'Users',
    category: 'advanced',
    context: 'User Management',
    component: () => import('./pages/advanced/user-management/UserManagementUsersPage.vue'),
  },
  {
    path: '/advanced/user-management/logout',
    title: 'Logout',
    category: 'advanced',
    context: 'User Management',
    component: () => import('./pages/advanced/user-management/UserManagementLogoutPage.vue'),
  },
  {
    path: '/advanced/collaboration/local',
    title: 'Local',
    category: 'advanced',
    context: 'Collaboration',
    component: () => import('./pages/advanced/collaboration/CollaborationLocalPage.vue'),
  },
  {
    path: '/advanced/collaboration/realtime',
    title: 'Realtime',
    category: 'advanced',
    context: 'Collaboration',
    component: () => import('./pages/advanced/collaboration/CollaborationRealtimePage.vue'),
  },
  {
    path: '/advanced/dynamic-objects/html',
    title: 'Html',
    category: 'advanced',
    context: 'Dynamic Objects',
    component: () => import('./pages/advanced/dynamic-objects/DynamicObjectsHtmlPage.vue'),
  },
  {
    path: '/advanced/dynamic-objects/component',
    title: 'Component',
    category: 'advanced',
    context: 'Dynamic Objects',
    component: () => import('./pages/advanced/dynamic-objects/DynamicObjectsComponentPage.vue'),
  },
  {
    path: '/advanced/dynamic-objects/iframe',
    title: 'Iframe',
    category: 'advanced',
    context: 'Dynamic Objects',
    component: () => import('./pages/advanced/dynamic-objects/DynamicObjectsIframePage.vue'),
  },
  {
    path: '/advanced/import-export/viewport-export',
    title: 'Viewport Export',
    category: 'advanced',
    context: 'Import Export',
    component: () => import('./pages/advanced/import-export/ImportExportViewportExportPage.vue'),
  },
  {
    path: '/advanced/import-export/workspace-export',
    title: 'Workspace Export',
    category: 'advanced',
    context: 'Import Export',
    component: () => import('./pages/advanced/import-export/ImportExportWorkspaceExportPage.vue'),
  },
  {
    path: '/advanced/import-export/workspace-import',
    title: 'Workspace Import',
    category: 'advanced',
    context: 'Import Export',
    component: () => import('./pages/advanced/import-export/ImportExportWorkspaceImportPage.vue'),
  },
  {
    path: '/customization/theming/apply',
    title: 'Apply',
    category: 'customization',
    context: 'Theming',
    component: () => import('./pages/customization/theming/ThemingApplyPage.vue'),
  },
  {
    path: '/customization/theming/custom',
    title: 'Custom',
    category: 'customization',
    context: 'Theming',
    component: () => import('./pages/customization/theming/ThemingCustomPage.vue'),
  },
  {
    path: '/customization/theming/listen',
    title: 'Listen',
    category: 'customization',
    context: 'Theming',
    component: () => import('./pages/customization/theming/ThemingListenPage.vue'),
  },
  {
    path: '/customization/fonts/register',
    title: 'Register',
    category: 'customization',
    context: 'Fonts',
    component: () => import('./pages/customization/fonts/FontsRegisterPage.vue'),
  },
  {
    path: '/customization/fonts/ui-font-family',
    title: 'Ui Font Family',
    category: 'customization',
    context: 'Fonts',
    component: () => import('./pages/customization/fonts/FontsUiFontFamilyPage.vue'),
  },
  {
    path: '/customization/icons/register',
    title: 'Register',
    category: 'customization',
    context: 'Icons',
    component: () => import('./pages/customization/icons/IconsRegisterPage.vue'),
  },
  {
    path: '/customization/icons/register-new',
    title: 'Register New',
    category: 'customization',
    context: 'Icons',
    component: () => import('./pages/customization/icons/IconsRegisterNewPage.vue'),
  },
  {
    path: '/customization/localization/switch',
    title: 'Switch',
    category: 'customization',
    context: 'Localization',
    component: () => import('./pages/customization/localization/LocalizationSwitchPage.vue'),
  },
  {
    path: '/customization/localization/custom',
    title: 'Custom',
    category: 'customization',
    context: 'Localization',
    component: () => import('./pages/customization/localization/LocalizationCustomPage.vue'),
  },
  {
    path: '/customization/localization/listen',
    title: 'Listen',
    category: 'customization',
    context: 'Localization',
    component: () => import('./pages/customization/localization/LocalizationListenPage.vue'),
  },
  {
    path: '/examples/object-explorer',
    title: 'Object Explorer',
    category: 'examples',
    component: () => import('./pages/examples/ObjectExplorerPage.vue'),
  },
  {
    path: '/examples/blueprint-defect-mapper',
    title: 'Blueprint Defect Mapper',
    category: 'examples',
    component: () => import('./pages/examples/BlueprintDefectMapperPage.vue'),
  },
  {
    path: '/examples/slideshow-presentation',
    title: 'Slideshow Presentation',
    category: 'examples',
    component: () => import('./pages/examples/SlideshowPresentationPage.vue'),
  },
  {
    path: '/examples/image-annotation-studio',
    title: 'Image Annotation Studio',
    category: 'examples',
    component: () => import('./pages/examples/ImageAnnotationStudioPage.vue'),
  },
] satisfies readonly DemoRoute[]