import { KritzelEngineState } from "../interfaces/engine-state.interface";

export const DEFAULT_ENGINE_STATE: KritzelEngineState = {
  activeTool: null,
  activeText: null,
  currentPath: null,
  copiedObjects: null,
  objectsOctree: null,
  selectionBox: null,
  selectionGroup: null,
  resizeHandleType: null,
  hasViewportChanged: false,
  isReady: false,
  isEnabled: true,
  isScaling: false,
  isPanning: false,
  isFocused: false,
  isSelecting: false,
  isResizing: false,
  isResizeHandleSelected: false,
  isRotating: false,
  isRotationHandleSelected: false,
  isDragging: false,
  isDrawing: false,
  isErasing: false,
  isWriting: false,
  isCtrlKeyPressed: false,
  isContextMenuVisible: false,
  contextMenuItems: [],
  contextMenuX: 0,
  contextMenuY: 0,
  skipContextMenu: false,
  debugInfo: {
    showObjectInfo: false,
    showViewportInfo: false,
    logCommands: false,
  },
  host: null,
  cursorX: 0,
  cursorY: 0,
  scale: 1,
  scaleMax: 1000,
  scaleMin: 0.0001,
  scaleStep: 0.05,
  startX: 0,
  startY: 0,
  translateX: 0,
  translateY: 0,
  viewportWidth: 0,
  viewportHeight: 0,
  historyBufferSize: 1000,
  longTouchTimeout: null,
  longTouchDelay: 300,
  pointers: new Map<number, PointerEvent>()
};