'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { type KritzelEngineCustomEvent, type KritzelTool } from "../../../../kritzel-stencil";
import { KritzelColorPalette as KritzelColorPaletteElement, defineCustomElement as defineKritzelColorPalette } from "../../../../kritzel-stencil/dist/components/kritzel-color-palette.js";
import { KritzelContextMenu as KritzelContextMenuElement, defineCustomElement as defineKritzelContextMenu } from "../../../../kritzel-stencil/dist/components/kritzel-context-menu.js";
import { KritzelControls as KritzelControlsElement, defineCustomElement as defineKritzelControls } from "../../../../kritzel-stencil/dist/components/kritzel-controls.js";
import { KritzelEditor as KritzelEditorElement, defineCustomElement as defineKritzelEditor } from "../../../../kritzel-stencil/dist/components/kritzel-editor.js";
import { KritzelEngine as KritzelEngineElement, defineCustomElement as defineKritzelEngine } from "../../../../kritzel-stencil/dist/components/kritzel-engine.js";
import { KritzelIcon as KritzelIconElement, defineCustomElement as defineKritzelIcon } from "../../../../kritzel-stencil/dist/components/kritzel-icon.js";
import { KritzelStrokeSize as KritzelStrokeSizeElement, defineCustomElement as defineKritzelStrokeSize } from "../../../../kritzel-stencil/dist/components/kritzel-stroke-size.js";

export type KritzelColorPaletteEvents = { onColorChange: EventName<CustomEvent<string>> };

export const KritzelColorPalette: StencilReactComponent<KritzelColorPaletteElement, KritzelColorPaletteEvents> = /*@__PURE__*/ createComponent<KritzelColorPaletteElement, KritzelColorPaletteEvents>({
    tagName: 'kritzel-color-palette',
    elementClass: KritzelColorPaletteElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onColorChange: 'colorChange' } as KritzelColorPaletteEvents,
    defineCustomElement: defineKritzelColorPalette
});

export type KritzelContextMenuEvents = { onActionSelected: EventName<CustomEvent<string>> };

export const KritzelContextMenu: StencilReactComponent<KritzelContextMenuElement, KritzelContextMenuEvents> = /*@__PURE__*/ createComponent<KritzelContextMenuElement, KritzelContextMenuEvents>({
    tagName: 'kritzel-context-menu',
    elementClass: KritzelContextMenuElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onActionSelected: 'actionSelected' } as KritzelContextMenuEvents,
    defineCustomElement: defineKritzelContextMenu
});

export type KritzelControlsEvents = NonNullable<unknown>;

export const KritzelControls: StencilReactComponent<KritzelControlsElement, KritzelControlsEvents> = /*@__PURE__*/ createComponent<KritzelControlsElement, KritzelControlsEvents>({
    tagName: 'kritzel-controls',
    elementClass: KritzelControlsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KritzelControlsEvents,
    defineCustomElement: defineKritzelControls
});

export type KritzelEditorEvents = NonNullable<unknown>;

export const KritzelEditor: StencilReactComponent<KritzelEditorElement, KritzelEditorEvents> = /*@__PURE__*/ createComponent<KritzelEditorElement, KritzelEditorEvents>({
    tagName: 'kritzel-editor',
    elementClass: KritzelEditorElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KritzelEditorEvents,
    defineCustomElement: defineKritzelEditor
});

export type KritzelEngineEvents = { onActiveToolChange: EventName<KritzelEngineCustomEvent<KritzelTool>> };

export const KritzelEngine: StencilReactComponent<KritzelEngineElement, KritzelEngineEvents> = /*@__PURE__*/ createComponent<KritzelEngineElement, KritzelEngineEvents>({
    tagName: 'kritzel-engine',
    elementClass: KritzelEngineElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onActiveToolChange: 'activeToolChange' } as KritzelEngineEvents,
    defineCustomElement: defineKritzelEngine
});

export type KritzelIconEvents = NonNullable<unknown>;

export const KritzelIcon: StencilReactComponent<KritzelIconElement, KritzelIconEvents> = /*@__PURE__*/ createComponent<KritzelIconElement, KritzelIconEvents>({
    tagName: 'kritzel-icon',
    elementClass: KritzelIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as KritzelIconEvents,
    defineCustomElement: defineKritzelIcon
});

export type KritzelStrokeSizeEvents = { onSizeChange: EventName<CustomEvent<number>> };

export const KritzelStrokeSize: StencilReactComponent<KritzelStrokeSizeElement, KritzelStrokeSizeEvents> = /*@__PURE__*/ createComponent<KritzelStrokeSizeElement, KritzelStrokeSizeEvents>({
    tagName: 'kritzel-stroke-size',
    elementClass: KritzelStrokeSizeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onSizeChange: 'sizeChange' } as KritzelStrokeSizeEvents,
    defineCustomElement: defineKritzelStrokeSize
});
