name: Deploy Docusaurus Docs and Angular App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"

      # --- Build Docusaurus Documentation ---
      - name: Install Docusaurus dependencies
        run: |
          cd website
          npm install

      - name: Build Docusaurus documentation
        run: |
          cd website
          npm run build
        env:
          Docusaurus_BASE_URL: /${{ github.event.repository.name }}/

      - name: Copy Docusaurus build to _site root
        run: |
          mkdir -p _site
          cp -r website/build/. _site/

      # --- Build Angular Application ---
      - name: Install Angular app dependencies
        run: |
          cd app
          npm install

      - name: Build Angular application
        run: |
          cd demo
          npm run build -- --base-href=/${{ github.event.repository.name }}/app/
        env: mkdir -p _site/app
          cp -r "demo/dist/demo/browser" _site/demo/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
